.\"                                      Hey, EMACS: -*- nroff -*-
.TH YLE-DOWNLOADER-GUI 1 "Apr 21, 2014"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
yle-downloader-gui \- GUI for yle-dl
.SH SYNOPSIS
.B yle-downloader-gui
.RI [ URL ]
.SH DESCRIPTION
\fByle-downloader-gui\fP is a graphical front-end for \fByle-dl\fP, a command line
application to download video and audio programs from the Finnish public
broadcast service Yle, more specifically its on-line services such as Yle Areena.
.SH PARAMETERS
.TP
.B URL
URL of the web page of video or audio in Yle Areena etc.
.SH SEE ALSO
\fByle-dl\fP(1),
/usr/share/docs/yle-downloader-gui/README*
.SH AUTHORS
yle-downloader-gui is being developed by Martin Pärtel, Jesse Jaara, Tomas
Strand, and Henrik Pitkälä; see https://github.com/mpartel/yle-downloader-gui.
.PP
This manual page was written by Henrik Pitkälä
<hpitkala@hotmail.com> for the Debian project (and may be
used by others).
